ALTER TABLE issues
  ADD COLUMN IF NOT EXISTS attachments_json LONGTEXT NULL,
  ADD COLUMN IF NOT EXISTS user_close_name VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS user_close_note TEXT NULL,
  ADD COLUMN IF NOT EXISTS user_close_sign MEDIUMTEXT NULL,
  ADD COLUMN IF NOT EXISTS user_closed_at DATETIME NULL;

ALTER TABLE employees
  ADD COLUMN IF NOT EXISTS end_date DATE NULL,
  ADD COLUMN IF NOT EXISTS transfer_date DATE NULL,
  ADD COLUMN IF NOT EXISTS resignation_link VARCHAR(1024) NULL;
